### PR TITLE
Center node cluster div and add search feature to containers

### PR DESCRIPTION
**Pull request by aloyr**
This is a simple change that centers the node cluster div on the screen.

image

### CODE REVIEW

**Comment by bariman** [comment]
looks good

**Comment by aloyr** [comment]
i also have another functionality worked out that we are using internally. perhaps that should be rolled as a separate PR?
test filter

**Comment by pahakalle** [comment]
@aloyr As a fun/cool thing to do,  make the search bar show when you click the "docker logo".

**Comment by aloyr** [comment]
ok, @pahakalle, I've polished the the search filter animation a bit and implemented the click event on the logo.

search filter

**Comment by aloyr** [comment]
@pahakalle are you able to merge this PR?

**Comment by pahakalle** [comment]
Only @ManoMarks can merge (not sure if someone else can also), i'm not part of the dev team.

**Comment by aloyr** [comment]
ok, thanks!

**Comment by BretFisher** [comment]
LGTM

**Pull request merged**
